### ISSUE TITLE
would be nice to be able to have decimals for increase and decrease values

### ISSUE THREAD

**Issue by CloudeLecaw** [Perotins/Blackjack#11]
is it possible to add decimal (one or two) values support for the increase and decrease buttons like 0.5 1.5 or 5.5?

i wanne use something like this:

```
# Sunflowers that are used to increase/decrease the bet value in menu
bet-modifiers:
   increaseValue1: 0.5
   increaseValue2: 1.0
   increaseValue3: 3.0
   decreaseValue1: 0.5
   decreaseValue2: 1.0
   decreaseValue3: 3.0
```
currently if i define this the GUI shows me -3 -1 0 +0 +1 +3 when i do this for the buttons.

so i switched it for now to 1 3 9

it would make sense because the win and beat windows allready shows 1 decimal after the full value

![Snag_122399b](https://github.com/Perotins/Blackjack/assets/12080017/0a6b7ff7-c92f-406b-bd2e-9792ecb92378)  ![image](https://github.com/Perotins/Blackjack/assets/12080017/88c88bb5-1e5b-4953-a835-220a8b0243a1)

by the way.. where this format is comming from $10.0  i was looking in the files and cant find a format like this with this $ infront of the value.
