### ISSUE TITLE
Pls make beating + - adjustable in config

### ISSUE THREAD

**Issue by CloudeLecaw** [Perotins/Blackjack#9]
We noticed that in the gui where you can define the beat

![image](https://github.com/Perotins/Blackjack/assets/12080017/00da0494-ea07-48e9-82a7-317fc7c74666)

There the sunflowers stand for -1000 -100 -10      +10  +100 and+1000
Our eceonomy works with much lower values. 1000 is very much there allready.
so we settet the beat limit currently to 31
So this result at the moment that a player can press 3 times the +10 or -10  but the othes are useless and suggest them they could higher by 100 or 1000
The game startwith beat to 1.0

So it would be nice for use if we could define the highering of the beats in config.
This is how it could look in config:
```
Beats:
  IncreaseValue1: 1000
  IncreaseValue2: 100
  IncreaseValue3: 10
  DecreaseValue1: 10
  DecreaseValue2: 100
  DecreaseValue3: 1000
```

So we could define it like

```
Beats:
  IncreaseValue1: 1
  IncreaseValue2: 10
  IncreaseValue3: 0.1
  DecreaseValue1: 0.1
  DecreaseValue2: 1
  DecreaseValue3: 10
```
What would result in seeing at the sunfolowers
like: -10 -1 -0.1    +0.1   +1   +10

Could you add this? <3
